version: "2"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/certs
      - /var/lib/hosting/vhost.d:/etc/nginx/vhost.d
      - /usr/share/nginx/html
    restart: always
    networks:
      - proxy-tier

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - proxy-tier

  app:
    build: .
    container_name: app
    volumes:
      - "./deploy/templates/conf.d/:/etc/nginx/conf.d"
    environment:
      VIRTUAL_HOST: realtime.fullstackweb.org
      LETSENCRYPT_HOST: realtime.fullstackweb.org
      LETSENCRYPT_EMAIL: us@fullstack.io
      NODE_ENV: production
    restart: always
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external:
      name: nginx-proxy
