version: "2"

services:
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - proxy-tier

  app:
    build: .
    container_name: app
    volumes:
      - "./deploy/templates/conf.d/:/etc/nginx/conf.d"
    environment:
      VIRTUAL_HOST: realtime.fullstackweb.org
      LETSENCRYPT_HOST: realtime.fullstackweb.org
      LETSENCRYPT_EMAIL: us@fullstack.io
      NODE_ENV: production
    restart: always
    ports:
      - 8001
    links:
      - redis
    networks:
      - proxy-tier
