version: "2"

services:
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - proxy-tier

  app:
    environment:
      VIRTUAL_HOST: realtime.fullstackweb.org
      LETSENCRYPT_HOST: realtime.fullstackweb.org
      LETSENCRYPT_EMAIL: us@fullstack.io
      NODE_ENV: production

networks:
  proxy-tier:
